CUDA_VISIBLE_DEVICES=1 torchrun --standalone --nnodes 1 --nproc-per-node=gpu vla-scripts/finetune.py \
  --vla_path openvla/openvla-7b \
  --data_root_dir /data/jiyufeng/openvla/datasets/ \
  --dataset_name sacson \
  --run_root_dir /data/jiyufeng/openvla/lora-instruct-scratch/run \
  --adapter_tmp_dir /data/jiyufeng/openvla/lora-instruct-scratch/adapter \
  --lora_rank 32 \
  --batch_size 16 \
  --grad_accumulation_steps 1  \
  --learning_rate 5e-4 \
  --image_aug False \
  --wandb_project openvla-instruct \
  --wandb_entity aliciaji1993 \
  --save_steps 10000 \
  --max_steps 200000 \
  --save_latest_checkpoint_only True