CUDA_VISIBLE_DEVICES=0 torchrun --standalone --nnodes 1 --nproc-per-node=gpu vla-scripts/finetune.py \
  --vla_path /data/jiyufeng/openvla/lora-instruct-scratch/run/openvla-7b+sacson+b16+lr-0.0005+lora-r32+dropout-0.0 \
  --data_root_dir /data/jiyufeng/openvla/datasets/ \
  --dataset_name sacson_homebot_v2_mixture_3 \
  --run_root_dir /data/jiyufeng/openvla/sacson_homebot_v2_mixture_3/run \
  --adapter_tmp_dir /data/jiyufeng/openvla/sacson_homebot_v2_mixture_3/adapter \
  --lora_rank 32 \
  --batch_size 16 \
  --grad_accumulation_steps 1  \
  --learning_rate 5e-4 \
  --image_aug False \
  --wandb_project sacson_homebot_v2_mixture \
  --wandb_entity aliciaji1993 \
  --save_steps 10000 \
  --max_steps 30000 \
  --save_latest_checkpoint_only True